### ISSUE TITLE
Adding sentences to Tatoeba

### ISSUE THREAD

**Issue by rwmpelstilzchen** [LBeaudoux/tatoebatools#7]
Hi,

What a wonderful library! I wish I had it when making [this](https://digitalwords.net/anki/tatoeba-audio/index.eng.html); it would have save me a lot of time… \^_\^

I see that currently Tatoeba Tools focuses on downloading and parsing, and I’m not sure whether you want the scope of the project to include this as well, but IMHO it would be great if you add a command for adding new sentences to Tatoeba. [There is no API](https://en.wiki.tatoeba.org/articles/show/faq#does-tatoeba-provide-an-api?), so I guess the only option right now is to mimic a web browser. There are libraries such as [MechanicalSoup](https://mechanicalsoup.readthedocs.io/) that provide tools for doing that.

Possible use cases are mass adding of sentences from existing projects. For example, there are [2270 Northern Sámi + Norwegian sentence pairs](http://gtweb.uit.no/webdict/nordsamisk_ordbok_offline.zip) from [Giellatekno](https://giellatekno.uit.no/) (CC-BY).

**Comment by LBeaudoux** [comment]
Hi Júda,

Thanks for your feedback! It's a pleasure to be in touch with someone who shares my interest in [Anki package](https://ankiweb.net/shared/info/181888029) generation. 😁

Sorry, but I don't plan to add any feature to post data on Tatoeba. I believe that releasing such a script would be a very bad idea since it would allow malevolent or overconfident contributors to become even more harmful. To be honest, I myself wrote a script that allows me to automatically log into my account and edit my lists. But I never use it to add sentences. 

If you are interested in mass importing sentences on Tatoeba, I suggest you to have a look at this [issue](https://github.com/Tatoeba/tatoeba2/issues/2256).

**Comment by rwmpelstilzchen** [comment]
Yeah, generating Anki decks is great fun 🙂⭐
My next big project, BTW, is to Ankify [Common Voice](https://commonvoice.mozilla.org/), but it will have to wait until I have time to implement it.

> Sorry, but I don't plan to add any feature to post data on Tatoeba.

I understand 🙂

> If you are interested in mass importing sentences on Tatoeba, I suggest you to have a look at this [issue](https://github.com/Tatoeba/tatoeba2/issues/2256).

Thanks!
This part of Tatoeba’s development doesn’t seem to move very fast, though…
